name: My Scraper Add-on
version: "1.0"
slug: my_scraper_addon
description: Scrapes a website and prints table data to the console.
url: "https://github.com/AtomProjects/ha-scraper-addon"
startup: application
boot: auto
stdin: true
options:
  website_url: "https://fws-leipzig.vpo.de/restrictedDayView"
  password: "FWS_LEIPZIG"
schema:
  website_url: str
  password: str
